title: "Let's talk about mental health"
author: Dunja Ivezic
email: ivezicdunja@gmail.com
description: > Let's talk about mental health site talks about.. well, you guessed it mental health! 
So are you in?

# social links
instagram_username: dunja_munjaa # DO NOT include the @ character, or else the build will fail!
github_username:  Munjara24 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
